linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    # - cyclop
    # - deadcode
    - decorder
    # - depguard
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    # - errorlint
    # - exhaustive
    # - exhaustivestruct
    # - exhaustruct
    # - forbidigo
    # - forcetypeassert
    # - funlen
    - gci
    # - gochecknoglobals
    - gochecknoinits
    # - gocognit
    - goconst
    # - gocritic
    # - gocyclo
    - godot
    # - godox
    # - goerr113
    - gofmt
    - gofumpt
    - prealloc
    # - predeclared
    - promlinter
    - reassign
    # - revive
    - rowserrcheck
    # - scopelint
    - sqlclosecheck
    # - staticcheck
    # - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    # - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    # - unparam
    - unused
    - usestdlibvars
    # - varcheck
    # - varnamelen
    - wastedassign
    - whitespace
    # - wrapcheck
    # - wsl
